# Generated by Django 5.2.7 on 2025-10-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ehr", "0003_practitioner_phone_practitioner_specialty_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="remarks",
            field=models.TextField(
                blank=True,
                help_text="Doctor's free-text remarks / clinical notes",
                null=True,
            ),
        ),
    ]
