# Generated by Django 5.2.7 on 2025-10-29 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ehr", "0004_observation_remarks"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="alert",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="observation",
            name="deidentified_patient_hash",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="observation",
            name="disease_key",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="observation",
            name="features",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="observation",
            name="risk_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="observation",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="observations",
                to="ehr.patient",
            ),
        ),
    ]
